[package]
name = "adder"
version = "0.1.0"
authors = ["muyiming <13511085358@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

add-one ={path = "../add-one"}

rand = "0.5.5"
